"""
Unit tests for DocumentGenerator.

All external I/O (DB, S3, Gemini, WeasyPrint) is mocked.
"""

from __future__ import annotations

import uuid
from datetime import date
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from app.models.enums import DocumentOrientation, DocumentStatus, DocumentType, Gender, VisaStatus
from app.services.document_generator import (
    DocumentGenerationError,
    DocumentGenerator,
    GeneratedDocumentOutput,
    _esc,
    _feature_name,
    _render_html,
    _render_rirekisho,
    _render_shokumu,
)
from app.services.file_storage import StorageError
from app.utils.pdf_generator import PDFGenerationError

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _mock_document(
    document_type: DocumentType = DocumentType.rirekisho,
    resume_id: uuid.UUID | None = None,
    job_context: dict | None = None,
) -> MagicMock:
    doc = MagicMock()
    doc.id = uuid.uuid4()
    doc.user_id = uuid.uuid4()
    doc.resume_id = resume_id or uuid.uuid4()
    doc.document_type = document_type
    doc.status = DocumentStatus.pending
    doc.job_context = job_context
    doc.orientation = DocumentOrientation.portrait
    return doc


def _mock_resume() -> MagicMock:
    r = MagicMock()
    r.id = uuid.uuid4()
    r.file_url = "resumes/user123/abc.pdf"
    r.mime_type = "application/pdf"
    return r


def _mock_user() -> MagicMock:
    """A complete User, as required for rirekisho generation."""
    u = MagicMock()
    u.full_name = "山田 太郎"
    u.email = "test@example.com"
    return u


def _mock_profile() -> MagicMock:
    """
    A complete Profile — passes _check_rirekisho_profile_complete by
    default (visa_status=none, so visa fields aren't required). Tests that
    need an incomplete profile or a held visa mutate the returned mock.
    """
    p = MagicMock()
    p.japanese_level = MagicMock()
    p.japanese_level.value = "N3"
    p.target_role = ["Software Engineer"]
    p.target_industry = ["IT"]
    p.years_experience = 5
    p.target_location = "Tokyo"
    p.name_kana = "ヤマダ タロウ"
    p.date_of_birth = date(1990, 1, 15)
    p.gender = Gender.male
    p.phone_number = "090-1234-5678"
    p.mailing_address = "東京都渋谷区"
    p.nationality = "インドネシア"
    p.visa_status = VisaStatus.none
    p.visa_category = None
    p.residence_card_expiration = None
    p.photo_storage_key = None
    p.hobbies = None
    p.special_skills = None
    p.personal_requests = None
    p.commute_time = None
    p.dependents = None
    return p


def _rirekisho_content() -> dict:
    """
    Shape of RirekishoResult.model_dump() — what Gemini's response actually
    produces. No personal/visa_info: those are assembled separately by
    DocumentGenerator, never generated by Gemini.
    """
    return {
        "education": [{"year": 2012, "month": 3, "entry": "○○大学 卒業"}],
        "work_history": [{"year": 2012, "month": 4, "entry": "株式会社ABC 入社"}],
        "qualifications": ["日本語能力試験N3"],
        "self_pr": "チームワークを大切にしています。",
        "motivation": "日本で働きたいと思っています。",
    }


def _rirekisho_render_content() -> dict:
    """
    Shape of the content dict AFTER DocumentGenerator.generate() merges in
    the DB-assembled personal/visa_info blocks — what _render_rirekisho()
    actually receives at render time. Distinct from _rirekisho_content(),
    which is what Gemini/RirekishoResult alone produces.
    """
    content = _rirekisho_content()
    content["personal"] = {
        "name_kanji": "山田 太郎",
        "name_kana": "ヤマダ タロウ",
        "date_of_birth": "平成2年1月15日",
        "age": 35,
        "gender": "男性",
        "address": "東京都渋谷区",
        "phone": "090-1234-5678",
        "email": "test@example.com",
        "photo_data_uri": None,
        "hobbies": "スノーボード",
        "special_skills": "Python",
        "personal_requests": "貴社の規定に従います。",
    }
    content["visa_info"] = {
        "nationality": "インドネシア",
        "visa_category": "技術・人文知識・国際業務",
        "residence_card_expiration": "2031年4月9日",
    }
    return content


def _shokumu_content() -> dict:
    return {
        "summary": "10年以上の経験を持つエンジニアです。",
        "companies": [
            {
                "company_name": "株式会社ABC",
                "industry": "情報通信業",
                "employee_count": "約500名",
                "roles": [
                    {
                        "role": "ソフトウェアエンジニア",
                        "period_start": "2015年4月",
                        "period_end": "現在",
                        "responsibilities": ["バックエンド開発を担当"],
                        "achievements": ["レスポンス速度を30%改善"],
                    }
                ],
            }
        ],
        "skills": {
            "technical": ["Python", "Java"],
            "languages": ["日本語（N3）", "英語（ビジネスレベル）"],
            "other": ["アジャイル開発"],
        },
        "self_pr": "チームワークを大切にしています。",
        "motivation": "日本のIT業界で貢献したいです。",
    }


# ---------------------------------------------------------------------------
# _esc
# ---------------------------------------------------------------------------


def test_esc_escapes_html_chars() -> None:
    assert (
        _esc("<script>alert('xss')</script>")
        == "&lt;script&gt;alert(&#x27;xss&#x27;)&lt;/script&gt;"
    )


def test_esc_handles_none() -> None:
    assert _esc(None) == ""


def test_esc_handles_integer() -> None:
    assert _esc(35) == "35"


# ---------------------------------------------------------------------------
# _feature_name
# ---------------------------------------------------------------------------


def test_feature_name_rirekisho() -> None:
    assert _feature_name(DocumentType.rirekisho) == "rirekisho"


def test_feature_name_shokumu() -> None:
    assert _feature_name(DocumentType.shokumukeirekisho) == "shokumu"


# ---------------------------------------------------------------------------
# HTML renderers
# ---------------------------------------------------------------------------


def test_render_rirekisho_contains_key_fields() -> None:
    html = _render_rirekisho(_rirekisho_render_content())
    assert "履　歴　書" in html
    assert "山田 太郎" in html
    assert "ヤマダ タロウ" in html
    assert "○○大学 卒業" in html
    assert "株式会社ABC 入社" in html
    assert "日本語能力試験N3" in html
    assert "チームワーク" in html


def test_render_rirekisho_title_uses_navy_accent() -> None:
    html = _render_rirekisho(_rirekisho_render_content())
    assert (
        '<h1 style="text-align:center; font-size:16pt; letter-spacing:0.3em; '
        'margin-bottom:8px; color:#1e3a5f;">' in html
    )


def test_render_rirekisho_shows_man_age_prefix() -> None:
    html = _render_rirekisho(_rirekisho_render_content())
    assert "満35歳" in html


def test_render_rirekisho_shows_visa_line_when_category_present() -> None:
    html = _render_rirekisho(_rirekisho_render_content())
    assert "インドネシア（技術・人文知識・国際業務）" in html
    assert "有効期限：2031年4月9日" in html


def test_render_rirekisho_shows_nationality_only_when_not_held() -> None:
    content = _rirekisho_render_content()
    content["visa_info"] = {
        "nationality": "インドネシア",
        "visa_category": None,
        "residence_card_expiration": None,
    }
    html = _render_rirekisho(content)
    assert "インドネシア" in html
    assert "有効期限" not in html


def test_render_rirekisho_shows_empty_photo_box_when_no_photo() -> None:
    html = _render_rirekisho(_rirekisho_render_content())
    assert "写真" in html
    assert "(縦40×横30mm)" in html
    assert "<img" not in html


def test_render_rirekisho_photo_placeholder_has_no_overflow() -> None:
    """
    Regression test for the overlap bug: the empty-photo placeholder box
    must clip its content, since the box is only 30x40mm and WeasyPrint
    does not clip overflowing content by default.
    """
    html = _render_rirekisho(_rirekisho_render_content())
    assert "overflow:hidden" in html


def test_render_rirekisho_shows_photo_when_present() -> None:
    content = _rirekisho_render_content()
    content["personal"]["photo_data_uri"] = "data:image/jpeg;base64,ZmFrZQ=="
    html = _render_rirekisho(content)
    assert '<img src="data:image/jpeg;base64,ZmFrZQ=="' in html
    assert "(縦40×横30mm)" not in html


def test_render_rirekisho_with_photo_actually_embeds_image_in_pdf() -> None:
    """
    Regression test: WeasyPrint silently drops a percentage-sized <img>
    inside a flex-centered container (a real bug this project hit) —
    string-matching the HTML for an <img> tag doesn't catch that, since
    WeasyPrint can silently omit it from the rendered PDF with no error.
    This test renders through the real PDF pipeline to catch that class
    of regression.
    """
    from app.utils.pdf_generator import html_to_pdf

    content = _rirekisho_render_content()
    content["personal"]["photo_data_uri"] = (
        "data:image/jpeg;base64,"
        "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAj/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k="
    )
    html = _render_rirekisho(content)
    pdf_bytes = html_to_pdf(html)
    assert b"/Subtype /Image" in pdf_bytes or b"/Subtype/Image" in pdf_bytes


def test_render_rirekisho_photo_box_does_not_overlap_personal_info_table() -> None:
    """
    Regression test: the personal-info table and the photo box used to sit
    side by side in a `display:flex` row (`<table style="flex:1;">` next to
    a fixed 30mm-wide photo box). WeasyPrint does not correctly negotiate a
    <table>'s width as a flex item: instead of shrinking the table to the
    space actually remaining after the fixed-width sibling, it computes the
    table's percentage-width columns against the *full* row width. The
    table's rightmost columns (生年月日, メール, 国籍・ビザ values) then
    render further right than the photo box's own left edge, so the opaque
    photo box -- painted after the table in document order -- visually
    covers real user data.

    This is verified by rendering through the real (unmocked) PDF pipeline
    and measuring the table's own cell BORDER lines in the PDF content
    stream, not by looking for filled rects: every <th>/<td> in this table
    has a `border` (from the shared _BASE_CSS), but only <th> cells get a
    `background-color` -- <td> *value* cells (where 生年月日/メール/
    国籍・ビザ's actual text lives) never emit a filled rect at all, only
    border-stroke line segments. An earlier version of this test measured
    filled rects instead and passed unchanged against the pre-fix buggy
    code (verified by checking out the parent commit and re-running it) --
    it could only see the narrow <th> label columns, which never reach far
    enough right to collide even when the table itself is badly oversized.
    Border lines exist for every cell (labels and values alike), so the
    rightmost vertical border line in the table's row band is a reliable
    proxy for how wide WeasyPrint actually computed the table, regardless
    of which specific cell holds the overflowing content.
    """
    import io
    import re

    import pypdf
    from app.utils.pdf_generator import html_to_pdf

    content = _rirekisho_render_content()
    content["personal"]["photo_data_uri"] = (
        "data:image/jpeg;base64,"
        "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAj/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k="
    )
    html = _render_rirekisho(content)
    pdf_bytes = html_to_pdf(html)

    reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
    contents = reader.pages[0].get_contents()
    assert contents is not None, "rendered PDF page has no content stream"
    raw = contents.get_data().decode("latin-1")

    # WeasyPrint's content stream opens with a `0.75 0 0 0.75 0 0 cm` matrix
    # (the CSS-px-to-PDF-pt scale, 72/96) that applies to every coordinate
    # drawn afterward -- must be included in the pt-to-mm conversion below,
    # or the measured coordinates are wrong by that same 0.75 factor.
    scale = 0.75
    pt_to_mm = 25.4 / 72

    # The photo box is drawn as a single filled rect at its declared 30x40mm
    # size -- this part of the measurement is reliable since the box always
    # has an explicit background/border, unlike the table's <td> cells.
    rects = [
        (
            float(x) * scale * pt_to_mm,
            float(y) * scale * pt_to_mm,
            float(w) * scale * pt_to_mm,
            float(h) * scale * pt_to_mm,
        )
        for x, y, w, h in re.findall(r"([\d.]+) ([\d.]+) ([\d.]+) ([\d.]+) re", raw)
    ]
    photo_box_candidates = [(x, y, w, h) for x, y, w, h in rects if 28 <= w <= 32 and 38 <= h <= 42]
    assert photo_box_candidates, "could not locate the photo box's rect in the PDF"
    photo_box_left_edge = min(x for x, _y, _w, _h in photo_box_candidates)
    photo_box_top = min(y for _x, y, _w, _h in photo_box_candidates)
    photo_box_bottom = max(y + h for _x, y, _w, h in photo_box_candidates)

    # Vertical border-stroke line segments: `x1 y1 m` (moveto) immediately
    # followed by `x2 y2 l` (lineto) with x1 == x2. These exist for every
    # table cell's left/right border, labels and values alike.
    line_pairs = re.findall(r"([\d.]+) ([\d.]+) m\s*\n([\d.]+) ([\d.]+) l", raw)
    vertical_borders_mm = [
        (
            float(x1) * scale * pt_to_mm,
            min(float(y1), float(y2)) * scale * pt_to_mm,
            max(float(y1), float(y2)) * scale * pt_to_mm,
        )
        for x1, y1, x2, y2 in line_pairs
        if abs(float(x1) - float(x2)) < 0.01
    ]
    assert vertical_borders_mm, "no vertical border lines found -- pdf_generator's output changed"

    # Only compare against border lines in the same vertical band as the
    # photo box (the personal-info table's rows) -- content further down
    # the page (e.g. the full-width 学歴・職歴 table) is legitimately
    # full-width and isn't part of this row, so it must be excluded or it
    # produces a false positive.
    def vertically_overlaps_photo_box(y_top: float, y_bottom: float) -> bool:
        return y_top < photo_box_bottom and y_bottom > photo_box_top

    borders_in_band = [
        x
        for x, y_top, y_bottom in vertical_borders_mm
        if vertically_overlaps_photo_box(y_top, y_bottom)
    ]
    assert borders_in_band, "no personal-info table border lines found to compare against"
    max_table_border_x = max(borders_in_band)
    assert max_table_border_x <= photo_box_left_edge + 1, (
        f"personal-info table's rightmost border reaches {max_table_border_x:.1f}mm, "
        f"past the photo box's left edge at {photo_box_left_edge:.1f}mm -- the table "
        "is overlapping the photo box"
    )


def test_render_rirekisho_shows_hobbies_and_skills() -> None:
    html = _render_rirekisho(_rirekisho_render_content())
    assert "スノーボード" in html
    assert "Python" in html
    assert "特技・趣味" in html


def test_render_rirekisho_shows_personal_requests() -> None:
    html = _render_rirekisho(_rirekisho_render_content())
    assert "貴社の規定に従います。" in html
    assert "本人希望記入欄" in html


def test_render_rirekisho_handles_blank_date_entry() -> None:
    content = _rirekisho_render_content()
    content["work_history"].append(
        {"year": None, "month": None, "entry": "店長として、店舗経営業務を行う"}
    )
    html = _render_rirekisho(content)
    assert "店長として、店舗経営業務を行う" in html
    # Should not crash trying to format a null date, and the row should
    # render with an empty date cell rather than "None年None月".
    assert "None" not in html


def test_render_shokumu_contains_key_fields() -> None:
    html = _render_shokumu(_shokumu_content())
    assert "職務経歴書" in html
    assert "株式会社ABC" in html
    assert "バックエンド開発を担当" in html
    assert "レスポンス速度を30%改善" in html
    assert "Python" in html
    assert "日本語（N3）" in html


def test_render_shokumu_title_uses_navy_accent() -> None:
    html = _render_shokumu(_shokumu_content())
    assert (
        '<h1 style="font-size:15pt; border-bottom:3px solid #1e3a5f; '
        'padding-bottom:4px; margin-bottom:8px; color:#1e3a5f;">' in html
    )


def test_render_html_dispatches_by_type() -> None:
    html_r = _render_html(
        DocumentType.rirekisho, _rirekisho_render_content(), DocumentOrientation.portrait
    )
    assert "履　歴　書" in html_r
    html_s = _render_html(
        DocumentType.shokumukeirekisho, _shokumu_content(), DocumentOrientation.portrait
    )
    assert "職務経歴書" in html_s


def test_render_html_dispatches_rirekisho_landscape() -> None:
    html = _render_html(
        DocumentType.rirekisho, _rirekisho_render_content(), DocumentOrientation.landscape
    )
    assert "page-break-before:always" in html


def test_render_rirekisho_escapes_html() -> None:
    content = _rirekisho_render_content()
    content["personal"]["name_kanji"] = "<b>Test</b>"
    html = _render_rirekisho(content)
    assert "<b>Test</b>" not in html
    assert "&lt;b&gt;" in html


def test_render_shokumu_handles_empty_achievements() -> None:
    content = _shokumu_content()
    content["companies"][0]["roles"][0]["achievements"] = []
    html = _render_shokumu(content)
    assert "職務経歴書" in html  # should not crash


def test_render_shokumu_shows_multiple_roles_for_one_company() -> None:
    content = _shokumu_content()
    content["companies"][0]["roles"] = [
        {
            "role": "技術派遣エンジニア",
            "period_start": "2020年9月",
            "period_end": "2022年6月",
            "responsibilities": ["基地局設計を担当"],
            "achievements": [],
        },
        {
            "role": "設計契約管理担当",
            "period_start": "2022年7月",
            "period_end": "現在",
            "responsibilities": ["契約管理業務を担当"],
            "achievements": [],
        },
    ]
    html = _render_shokumu(content)
    assert "技術派遣エンジニア" in html
    assert "設計契約管理担当" in html
    assert html.count("株式会社ABC") == 1  # company name shown once, not per role


# ---------------------------------------------------------------------------
# _build_rirekisho_personal — photo, hobbies, personal_requests assembly
# ---------------------------------------------------------------------------


def test_build_rirekisho_personal_defaults_personal_requests() -> None:
    from app.services.document_generator import _build_rirekisho_personal

    user = _mock_user()
    profile = _mock_profile()
    profile.photo_storage_key = None
    profile.hobbies = None
    profile.special_skills = None
    profile.personal_requests = None

    personal = _build_rirekisho_personal(user, profile)
    assert personal["personal_requests"] == "貴社の規定に従います。"
    assert personal["photo_data_uri"] is None
    assert personal["hobbies"] is None


def test_build_rirekisho_personal_uses_custom_personal_requests() -> None:
    from app.services.document_generator import _build_rirekisho_personal

    user = _mock_user()
    profile = _mock_profile()
    profile.photo_storage_key = None
    profile.hobbies = "スノーボード"
    profile.special_skills = "Python"
    profile.personal_requests = "リモートワークを希望します。"

    personal = _build_rirekisho_personal(user, profile)
    assert personal["personal_requests"] == "リモートワークを希望します。"
    assert personal["hobbies"] == "スノーボード"
    assert personal["special_skills"] == "Python"


def test_build_rirekisho_personal_includes_commute_time_and_dependents_when_set() -> None:
    from app.services.document_generator import _build_rirekisho_personal

    user = _mock_user()
    profile = _mock_profile()
    profile.commute_time = "電車で約45分"
    profile.dependents = "2名"

    personal = _build_rirekisho_personal(user, profile)
    assert personal["commute_time"] == "電車で約45分"
    assert personal["dependents"] == "2名"


def test_build_rirekisho_personal_omits_commute_time_and_dependents_when_blank() -> None:
    from app.services.document_generator import _build_rirekisho_personal

    user = _mock_user()
    profile = _mock_profile()
    profile.commute_time = None
    profile.dependents = None

    personal = _build_rirekisho_personal(user, profile)
    assert personal["commute_time"] is None
    assert personal["dependents"] is None


def test_build_rirekisho_personal_embeds_photo_as_data_uri() -> None:
    from app.services.document_generator import _build_rirekisho_personal

    user = _mock_user()
    profile = _mock_profile()
    profile.photo_storage_key = "photos/u1/abc.jpg"
    profile.hobbies = None
    profile.special_skills = None
    profile.personal_requests = None

    with patch(
        "app.services.document_generator.file_storage.download",
        return_value=b"fake-jpeg-bytes",
    ):
        personal = _build_rirekisho_personal(user, profile)

    assert personal["photo_data_uri"] == "data:image/jpeg;base64,ZmFrZS1qcGVnLWJ5dGVz"


def test_build_rirekisho_personal_photo_download_failure_omits_photo() -> None:
    from app.services.document_generator import _build_rirekisho_personal

    user = _mock_user()
    profile = _mock_profile()
    profile.photo_storage_key = "photos/u1/abc.jpg"
    profile.hobbies = None
    profile.special_skills = None
    profile.personal_requests = None

    with patch(
        "app.services.document_generator.file_storage.download",
        side_effect=StorageError("boom"),
    ):
        personal = _build_rirekisho_personal(user, profile)

    assert personal["photo_data_uri"] is None


# ---------------------------------------------------------------------------
# DocumentGenerator.generate — success path (rirekisho)
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_generate_rirekisho_returns_output() -> None:
    doc = _mock_document(DocumentType.rirekisho)
    resume = _mock_resume()
    user = _mock_user()
    profile = _mock_profile()

    generator = DocumentGenerator()

    with (
        patch("app.services.document_generator.DocumentRepository") as MockDocRepo,
        patch("app.services.document_generator.ResumeRepository") as MockResumeRepo,
        patch("app.services.document_generator.ProfileRepository") as MockProfileRepo,
        patch("app.services.document_generator.UserRepository") as MockUserRepo,
        patch.object(generator, "_fetch_and_extract", new=AsyncMock(return_value="resume text")),
        patch("app.services.document_generator.usage_tracker.check_budget", new=AsyncMock()),
        patch.object(
            generator,
            "_call_ai",
            new=AsyncMock(return_value=('{"ok": true}', 1200, 800)),
        ),
        patch.object(
            generator,
            "_parse_response",
            return_value=_rirekisho_content(),
        ),
        patch("app.services.document_generator.html_to_pdf", return_value=b"%PDF"),
        patch(
            "app.services.document_generator.file_storage.upload_document",
            return_value="documents/u/rirekisho/abc.pdf",
        ),
        patch("app.services.document_generator.usage_tracker.record", new=AsyncMock()),
    ):
        MockDocRepo.return_value.get = AsyncMock(return_value=doc)
        MockResumeRepo.return_value.get_owned = AsyncMock(return_value=resume)
        MockProfileRepo.return_value.get_by_user_id = AsyncMock(return_value=profile)
        MockUserRepo.return_value.get = AsyncMock(return_value=user)

        result = await generator.generate(doc.id, doc.user_id, AsyncMock())

    assert isinstance(result, GeneratedDocumentOutput)
    assert result.file_url == "documents/u/rirekisho/abc.pdf"
    assert result.input_tokens == 1200
    assert result.output_tokens == 800

    # Personal info came from User/Profile, not from the (garbage) mocked
    # Gemini response — proves the DB-assembly path, not LLM output.
    assert result.content["personal"]["name_kanji"] == "山田 太郎"
    assert result.content["personal"]["name_kana"] == "ヤマダ タロウ"
    assert result.content["personal"]["date_of_birth"] == "平成2年1月15日"
    assert result.content["personal"]["gender"] == "男性"
    assert result.content["personal"]["email"] == "test@example.com"
    # Age is computed as of today, so recompute the expected value the same
    # way rather than hardcoding a number that would go stale over time.
    dob = date(1990, 1, 15)
    today = date.today()
    expected_age = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
    assert result.content["personal"]["age"] == expected_age
    assert result.content["visa_info"]["nationality"] == "インドネシア"
    assert result.content["visa_info"]["visa_category"] is None


# ---------------------------------------------------------------------------
# DocumentGenerator.generate — rirekisho profile-completeness failures
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_generate_rirekisho_raises_when_profile_incomplete() -> None:
    doc = _mock_document(DocumentType.rirekisho)
    resume = _mock_resume()
    user = _mock_user()
    profile = _mock_profile()
    profile.date_of_birth = None  # incomplete

    generator = DocumentGenerator()

    with (
        patch("app.services.document_generator.DocumentRepository") as MockDocRepo,
        patch("app.services.document_generator.ResumeRepository") as MockResumeRepo,
        patch("app.services.document_generator.ProfileRepository") as MockProfileRepo,
        patch("app.services.document_generator.UserRepository") as MockUserRepo,
    ):
        MockDocRepo.return_value.get = AsyncMock(return_value=doc)
        MockResumeRepo.return_value.get_owned = AsyncMock(return_value=resume)
        MockProfileRepo.return_value.get_by_user_id = AsyncMock(return_value=profile)
        MockUserRepo.return_value.get = AsyncMock(return_value=user)

        # No _fetch_and_extract/_call_ai mocks — the completeness check must
        # raise before either would ever be reached. If it doesn't run early
        # enough, this test fails with an unmocked-call error instead of
        # the expected DocumentGenerationError, which is itself the proof.
        with pytest.raises(DocumentGenerationError, match="Complete your profile"):
            await generator.generate(doc.id, doc.user_id, AsyncMock())


@pytest.mark.asyncio
async def test_generate_rirekisho_raises_when_visa_held_but_category_missing() -> None:
    doc = _mock_document(DocumentType.rirekisho)
    resume = _mock_resume()
    user = _mock_user()
    profile = _mock_profile()
    profile.visa_status = VisaStatus.held
    profile.visa_category = None  # incomplete for held status
    profile.residence_card_expiration = date(2031, 4, 9)

    generator = DocumentGenerator()

    with (
        patch("app.services.document_generator.DocumentRepository") as MockDocRepo,
        patch("app.services.document_generator.ResumeRepository") as MockResumeRepo,
        patch("app.services.document_generator.ProfileRepository") as MockProfileRepo,
        patch("app.services.document_generator.UserRepository") as MockUserRepo,
    ):
        MockDocRepo.return_value.get = AsyncMock(return_value=doc)
        MockResumeRepo.return_value.get_owned = AsyncMock(return_value=resume)
        MockProfileRepo.return_value.get_by_user_id = AsyncMock(return_value=profile)
        MockUserRepo.return_value.get = AsyncMock(return_value=user)

        with pytest.raises(DocumentGenerationError, match="Complete your profile"):
            await generator.generate(doc.id, doc.user_id, AsyncMock())


@pytest.mark.asyncio
async def test_generate_rirekisho_raises_when_age_out_of_range() -> None:
    doc = _mock_document(DocumentType.rirekisho)
    resume = _mock_resume()
    user = _mock_user()
    profile = _mock_profile()
    profile.date_of_birth = date(1930, 1, 1)  # computed age far outside 16-80

    generator = DocumentGenerator()

    with (
        patch("app.services.document_generator.DocumentRepository") as MockDocRepo,
        patch("app.services.document_generator.ResumeRepository") as MockResumeRepo,
        patch("app.services.document_generator.ProfileRepository") as MockProfileRepo,
        patch("app.services.document_generator.UserRepository") as MockUserRepo,
    ):
        MockDocRepo.return_value.get = AsyncMock(return_value=doc)
        MockResumeRepo.return_value.get_owned = AsyncMock(return_value=resume)
        MockProfileRepo.return_value.get_by_user_id = AsyncMock(return_value=profile)
        MockUserRepo.return_value.get = AsyncMock(return_value=user)

        # No _fetch_and_extract/_call_ai mocks — same early-exit proof as
        # the other completeness tests above.
        with pytest.raises(DocumentGenerationError, match="Complete your profile"):
            await generator.generate(doc.id, doc.user_id, AsyncMock())


# ---------------------------------------------------------------------------
# DocumentGenerator.generate — other failure cases
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_generate_raises_when_document_not_found() -> None:
    generator = DocumentGenerator()
    with patch("app.services.document_generator.DocumentRepository") as MockDocRepo:
        MockDocRepo.return_value.get = AsyncMock(return_value=None)
        with pytest.raises(DocumentGenerationError, match="not found"):
            await generator.generate(uuid.uuid4(), uuid.uuid4(), AsyncMock())


@pytest.mark.asyncio
async def test_generate_raises_when_resume_id_is_null() -> None:
    doc = _mock_document()
    doc.resume_id = None

    generator = DocumentGenerator()
    with patch("app.services.document_generator.DocumentRepository") as MockDocRepo:
        MockDocRepo.return_value.get = AsyncMock(return_value=doc)
        with pytest.raises(DocumentGenerationError, match="deleted"):
            await generator.generate(doc.id, doc.user_id, AsyncMock())


@pytest.mark.asyncio
async def test_generate_raises_when_resume_not_owned() -> None:
    doc = _mock_document()
    generator = DocumentGenerator()

    with (
        patch("app.services.document_generator.DocumentRepository") as MockDocRepo,
        patch("app.services.document_generator.ResumeRepository") as MockResumeRepo,
        patch("app.services.document_generator.ProfileRepository") as MockProfileRepo,
    ):
        MockDocRepo.return_value.get = AsyncMock(return_value=doc)
        MockResumeRepo.return_value.get_owned = AsyncMock(return_value=None)
        MockProfileRepo.return_value.get_by_user_id = AsyncMock(return_value=None)

        with pytest.raises(DocumentGenerationError, match="not found or not owned"):
            await generator.generate(doc.id, doc.user_id, AsyncMock())


@pytest.mark.asyncio
async def test_generate_raises_on_ai_error() -> None:
    """
    Uses shokumu, not rirekisho — this test exercises generic AI-error
    handling, not rirekisho-specific profile completeness, and shokumu has
    no personal-info section so the completeness check never runs for it.
    """
    from app.services.ai.client import AIError

    doc = _mock_document(DocumentType.shokumukeirekisho)
    resume = _mock_resume()
    generator = DocumentGenerator()

    with (
        patch("app.services.document_generator.DocumentRepository") as MockDocRepo,
        patch("app.services.document_generator.ResumeRepository") as MockResumeRepo,
        patch("app.services.document_generator.ProfileRepository") as MockProfileRepo,
        patch.object(generator, "_fetch_and_extract", new=AsyncMock(return_value="text")),
        patch("app.services.document_generator.usage_tracker.check_budget", new=AsyncMock()),
        patch.object(generator, "_call_ai", new=AsyncMock(side_effect=AIError("timeout"))),
    ):
        MockDocRepo.return_value.get = AsyncMock(return_value=doc)
        MockResumeRepo.return_value.get_owned = AsyncMock(return_value=resume)
        MockProfileRepo.return_value.get_by_user_id = AsyncMock(return_value=None)

        with pytest.raises(DocumentGenerationError, match="AI generation failed"):
            await generator.generate(doc.id, doc.user_id, AsyncMock())


@pytest.mark.asyncio
async def test_generate_raises_on_pdf_error() -> None:
    """Uses shokumu for the same reason as test_generate_raises_on_ai_error above."""
    doc = _mock_document(DocumentType.shokumukeirekisho)
    resume = _mock_resume()
    generator = DocumentGenerator()

    with (
        patch("app.services.document_generator.DocumentRepository") as MockDocRepo,
        patch("app.services.document_generator.ResumeRepository") as MockResumeRepo,
        patch("app.services.document_generator.ProfileRepository") as MockProfileRepo,
        patch.object(generator, "_fetch_and_extract", new=AsyncMock(return_value="text")),
        patch("app.services.document_generator.usage_tracker.check_budget", new=AsyncMock()),
        patch.object(generator, "_call_ai", new=AsyncMock(return_value=("{}", 100, 50))),
        patch.object(generator, "_parse_response", return_value=_shokumu_content()),
        patch(
            "app.services.document_generator.html_to_pdf",
            side_effect=PDFGenerationError("font missing"),
        ),
    ):
        MockDocRepo.return_value.get = AsyncMock(return_value=doc)
        MockResumeRepo.return_value.get_owned = AsyncMock(return_value=resume)
        MockProfileRepo.return_value.get_by_user_id = AsyncMock(return_value=None)

        with pytest.raises(DocumentGenerationError, match="PDF rendering failed"):
            await generator.generate(doc.id, doc.user_id, AsyncMock())
