"""
Document generation service.

Orchestrates the full pipeline for generating a Japanese career document:

  1. Load the GeneratedDocument row + Resume + Profile from DB
  2. Fetch resume file bytes from S3 and extract plain text
  3. Call the appropriate prompt builder (rirekisho / shokumu)
  4. Check AI usage budget
  5. Call Gemini via AIClient
  6. Parse and validate the JSON response
  7. For rirekisho, assemble the personal/visa_info blocks directly from
     the database (never from Gemini) and merge them into the content
  8. Render structured JSON → HTML template
  9. Convert HTML → PDF bytes via WeasyPrint, offloaded to a thread (it's
     CPU-bound and would otherwise block the event loop)
  10. Upload PDF to S3
  11. Return GeneratedDocumentOutput (caller writes it to DB)

Called from a FastAPI BackgroundTasks callback
(app.workers.document_tasks._run_generation), not a Celery task. It does
NOT update the document status — that is the caller's responsibility so
that failed partial runs can be recorded cleanly.
"""

from __future__ import annotations

import asyncio
import base64
import logging
import time
from dataclasses import dataclass
from datetime import date
from typing import TYPE_CHECKING, Any
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models.enums import DocumentType, Gender, VisaStatus
from app.repositories.document import DocumentRepository
from app.repositories.resume import ResumeRepository
from app.repositories.user import ProfileRepository, UserRepository
from app.services.ai.client import AIError, ai_client
from app.services.ai.response_parser import ResponseParseError, parse_response
from app.services.ai.usage_tracker import AIBudgetError, usage_tracker
from app.services.file_storage import StorageError, file_storage
from app.services.resume_parser import ParseError, extract_text
from app.services.rirekisho_completeness import rirekisho_missing_fields
from app.utils.pdf_generator import PDFGenerationError, html_to_pdf

if TYPE_CHECKING:
    from app.models.user import Profile, User
    from app.services.ai.prompts.rirekisho import RirekishoResult
    from app.services.ai.prompts.shokumu import ShokumuResult

logger = logging.getLogger(__name__)


class DocumentGenerationError(Exception):
    """Raised when any step of the pipeline fails."""


@dataclass
class GeneratedDocumentOutput:
    content: dict[str, Any]
    file_url: str
    ai_model: str
    input_tokens: int
    output_tokens: int


class DocumentGenerator:
    """
    Stateless service — one instance shared across tasks.
    Each `generate()` call is fully self-contained.
    """

    async def generate(
        self,
        document_id: UUID,
        user_id: UUID,
        db: AsyncSession,
    ) -> GeneratedDocumentOutput:
        """
        Run the full generation pipeline for a single document.
        Raises DocumentGenerationError with a human-readable message on any failure.
        """
        # -- Load document row
        doc_repo = DocumentRepository(db)
        doc = await doc_repo.get(document_id)
        if doc is None:
            raise DocumentGenerationError(f"Document {document_id} not found")

        if doc.resume_id is None:
            raise DocumentGenerationError(
                "Source resume was deleted before generation could complete"
            )

        # -- Load resume
        resume_repo = ResumeRepository(db)
        resume = await resume_repo.get_owned(doc.resume_id, user_id)
        if resume is None:
            raise DocumentGenerationError(
                f"Resume {doc.resume_id} not found or not owned by user {user_id}"
            )

        # -- Load profile (optional — used for prompt enrichment)
        profile_repo = ProfileRepository(db)
        profile = await profile_repo.get_by_user_id(user_id)
        profile_data: dict[str, Any] | None = None
        if profile is not None:
            profile_data = {
                "japanese_level": profile.japanese_level.value,
                "target_role": profile.target_role,
                "target_industry": profile.target_industry,
                "years_experience": profile.years_experience,
                "target_location": profile.target_location,
            }

        # -- For rirekisho, personal/visa info is sourced from the database,
        # not generated by Gemini — load the user and verify the profile is
        # complete before doing any (paid) AI work.
        user: User | None = None
        if doc.document_type == DocumentType.rirekisho:
            user_repo = UserRepository(db)
            user = await user_repo.get(user_id)
            if user is None:
                raise DocumentGenerationError(f"User {user_id} not found")
            _check_rirekisho_profile_complete(user, profile)

        # -- Fetch resume bytes from S3 and extract text
        resume_text = await self._fetch_and_extract(resume.file_url, resume.mime_type)

        # -- Resolve job posting text from job_context if present
        job_posting_text: str | None = None
        if doc.job_context:
            job_posting_text = doc.job_context.get("translated_description")

        # -- Budget check
        feature = _feature_name(doc.document_type)
        try:
            await usage_tracker.check_budget(user_id, feature, db)
        except AIBudgetError as exc:
            raise DocumentGenerationError(str(exc)) from exc

        # -- Build prompts and call Gemini
        t0 = time.monotonic()
        try:
            response_text, input_tokens, output_tokens = await self._call_ai(
                doc.document_type,
                resume_text,
                profile_data,
                job_posting_text,
            )
        except AIError as exc:
            raise DocumentGenerationError(f"AI generation failed: {exc}") from exc
        latency_ms = int((time.monotonic() - t0) * 1000)

        # -- Parse response
        content = self._parse_response(doc.document_type, response_text)

        # -- For rirekisho, merge in the deterministic personal/visa blocks
        # assembled from the database — Gemini never produces this data.
        if doc.document_type == DocumentType.rirekisho:
            if user is None or profile is None:
                raise DocumentGenerationError(
                    "Missing user or profile data for rirekisho generation"
                )
            content["personal"] = _build_rirekisho_personal(user, profile)
            content["visa_info"] = _build_rirekisho_visa_info(profile)

        # -- Render HTML → PDF. Offloaded to a thread: WeasyPrint is
        # CPU-bound, and this method runs inline on the event loop as a
        # FastAPI background task — calling it directly here would stall
        # every other in-flight request for the duration of rendering.
        html = _render_html(doc.document_type, content)
        try:
            pdf_bytes = await asyncio.to_thread(html_to_pdf, html)
        except PDFGenerationError as exc:
            raise DocumentGenerationError(f"PDF rendering failed: {exc}") from exc

        # -- Upload PDF to S3
        try:
            s3_key = file_storage.upload_document(
                file_bytes=pdf_bytes,
                user_id=user_id,
                document_type=doc.document_type.value,
            )
        except StorageError as exc:
            raise DocumentGenerationError(f"S3 upload failed: {exc}") from exc

        # -- Record usage (never raises)
        await usage_tracker.record(
            user_id=user_id,
            feature=feature,
            model=settings.gemini_default_model,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            latency_ms=latency_ms,
            db=db,
        )

        return GeneratedDocumentOutput(
            content=content,
            file_url=s3_key,
            ai_model=settings.gemini_default_model,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _fetch_and_extract(self, s3_key: str, mime_type: str) -> str:
        """Fetch resume bytes from S3 and extract plain text."""
        try:
            file_bytes = file_storage.download(s3_key)
        except StorageError as exc:
            raise DocumentGenerationError("Failed to fetch resume file. Please try again.") from exc

        try:
            return extract_text(file_bytes, mime_type)
        except ParseError as exc:
            raise DocumentGenerationError(
                "Could not read this resume file. Please re-upload it in a supported format."
            ) from exc

    async def _call_ai(
        self,
        document_type: DocumentType,
        resume_text: str,
        profile_data: dict[str, Any] | None,
        job_posting_text: str | None,
    ) -> tuple[str, int, int]:
        if document_type == DocumentType.rirekisho:
            from app.services.ai.prompts.rirekisho import (
                build_system_prompt,
                build_user_prompt,
            )

            max_tokens = 2500
        else:
            from app.services.ai.prompts.shokumu import (
                build_system_prompt,
                build_user_prompt,
            )

            max_tokens = 3000

        system = build_system_prompt()
        user = build_user_prompt(
            resume_text,
            profile_data=profile_data,
            job_posting_text=job_posting_text,
        )
        return await ai_client.generate(
            system,
            user,
            max_tokens=max_tokens,
            feature=_feature_name(document_type),
        )

    def _parse_response(self, document_type: DocumentType, response_text: str) -> dict[str, Any]:
        result: RirekishoResult | ShokumuResult
        try:
            if document_type == DocumentType.rirekisho:
                from app.services.ai.prompts.rirekisho import RirekishoResult

                result = parse_response(response_text, RirekishoResult)
            else:
                from app.services.ai.prompts.shokumu import ShokumuResult

                result = parse_response(response_text, ShokumuResult)
        except ResponseParseError as exc:
            raise DocumentGenerationError(f"Response validation failed: {exc}") from exc

        return result.model_dump()


# ---------------------------------------------------------------------------
# Rirekisho personal-info assembly
#
# Personal/visa info is never generated by Gemini (see
# app.services.ai.prompts.rirekisho) — it's assembled here directly from
# verified account/profile data, which is deterministic and has zero
# hallucination risk for fields that are just a verbatim copy.
# ---------------------------------------------------------------------------

_DEFAULT_PERSONAL_REQUESTS = "貴社の規定に従います。"


def _check_rirekisho_profile_complete(user: User, profile: Profile | None) -> None:
    """
    Raise DocumentGenerationError listing every missing field if the profile
    isn't complete enough to generate a rirekisho. Called before any AI work
    so a doomed generation fails fast and cheaply, with a message that lets
    the user fix everything in one pass instead of one field at a time.
    """
    missing = rirekisho_missing_fields(user, profile)
    if missing:
        labels = [m["label"] for m in missing]
        raise DocumentGenerationError(
            "Complete your profile before generating a 履歴書. Missing: " + ", ".join(labels) + "."
        )


def _build_rirekisho_personal(user: User, profile: Profile) -> dict[str, Any]:
    """Assemble the rirekisho personal-info block from User/Profile."""
    from pydantic import ValidationError

    from app.services.ai.prompts.rirekisho import RirekishoPersonal
    from app.utils.japanese_date import format_wareki_full

    dob = profile.date_of_birth
    if dob is None:
        raise DocumentGenerationError("date_of_birth missing after completeness check")
    if profile.gender is None:
        raise DocumentGenerationError("gender missing after completeness check")

    today = date.today()
    age = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
    gender_ja = "男性" if profile.gender == Gender.male else "女性"

    photo_data_uri: str | None = None
    if profile.photo_storage_key:
        try:
            photo_bytes = file_storage.download(profile.photo_storage_key)
            ext = profile.photo_storage_key.rsplit(".", 1)[-1].lower()
            mime = "image/png" if ext == "png" else "image/jpeg"
            photo_data_uri = f"data:{mime};base64,{base64.b64encode(photo_bytes).decode('ascii')}"
        except StorageError:
            logger.warning(
                "Failed to fetch rirekisho photo for user_id=%s; rendering without it", user.id
            )

    try:
        personal = RirekishoPersonal(
            name_kanji=user.full_name or "",
            name_kana=profile.name_kana or "",
            date_of_birth=format_wareki_full(dob.year, dob.month, dob.day),
            age=age,
            gender=gender_ja,
            address=profile.mailing_address or "",
            phone=profile.phone_number or "",
            email=user.email,
            photo_data_uri=photo_data_uri,
            hobbies=profile.hobbies or None,
            special_skills=profile.special_skills or None,
            personal_requests=profile.personal_requests or _DEFAULT_PERSONAL_REQUESTS,
        )
    except ValidationError as exc:
        raise DocumentGenerationError(f"Invalid personal info for rirekisho: {exc}") from exc
    return personal.model_dump()


def _build_rirekisho_visa_info(profile: Profile) -> dict[str, Any]:
    """
    Assemble the 国籍・ビザ block. visa_category/residence_card_expiration
    are only populated when visa_status = held; the template shows just the
    nationality otherwise.
    """
    from app.services.ai.prompts.rirekisho import RirekishoVisaInfo

    visa_category: str | None = None
    residence_card_expiration: str | None = None

    if profile.visa_status == VisaStatus.held:
        if not profile.visa_category:
            raise DocumentGenerationError("visa_category missing after completeness check")
        if profile.residence_card_expiration is None:
            raise DocumentGenerationError(
                "residence_card_expiration missing after completeness check"
            )
        visa_category = profile.visa_category
        d = profile.residence_card_expiration
        residence_card_expiration = f"{d.year}年{d.month}月{d.day}日"

    visa_info = RirekishoVisaInfo(
        nationality=profile.nationality,
        visa_category=visa_category,
        residence_card_expiration=residence_card_expiration,
    )
    return visa_info.model_dump()


# ---------------------------------------------------------------------------
# HTML renderers
# ---------------------------------------------------------------------------


def _render_html(document_type: DocumentType, content: dict[str, Any]) -> str:
    if document_type == DocumentType.rirekisho:
        return _render_rirekisho(content)
    return _render_shokumu(content)


def _render_rirekisho(c: dict[str, Any]) -> str:
    p = c.get("personal", {})
    v = c.get("visa_info", {})

    from app.utils.japanese_date import format_wareki_date

    def _entry_row(entry: dict[str, Any]) -> str:
        year, month = entry.get("year"), entry.get("month")
        date_cell = (
            format_wareki_date(year, month) if year is not None and month is not None else ""
        )
        return f"<tr><td>{date_cell}</td><td>{_esc(entry['entry'])}</td></tr>"

    education_rows = "".join(_entry_row(e) for e in c.get("education", []))
    work_rows = "".join(_entry_row(w) for w in c.get("work_history", []))
    qualifications = "".join(f"<li>{_esc(q)}</li>" for q in c.get("qualifications", []))

    visa_category = v.get("visa_category")
    if visa_category:
        visa_line = (
            f"{v.get('nationality', '')}（{visa_category}）"
            f"　有効期限：{v.get('residence_card_expiration', '')}"
        )
    else:
        visa_line = v.get("nationality", "")

    photo_data_uri = p.get("photo_data_uri")
    if photo_data_uri:
        # WeasyPrint silently drops a percentage-sized <img> when its
        # container uses flexbox centering (align-items/justify-content) —
        # a known limitation with replaced elements in flex layouts. Use
        # plain block sizing here instead; flex centering is only safe for
        # the icon+text placeholder case below.
        photo_box_style = (
            "width:30mm; height:40mm; flex-shrink:0; border:1px solid #1e3a5f; overflow:hidden;"
        )
        photo_box_inner = (
            f'<img src="{_esc(photo_data_uri)}" '
            'style="width:100%; height:100%; object-fit:cover; display:block;" />'
        )
    else:
        photo_box_style = (
            "width:30mm; height:40mm; flex-shrink:0; border:1.5px dashed #1e3a5f; "
            "overflow:hidden; display:flex; flex-direction:column; align-items:center; "
            "justify-content:center; text-align:center; gap:2mm; color:#1e3a5f; padding:2px;"
        )
        photo_box_inner = (
            '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" '
            'stroke="#1e3a5f" stroke-width="1.5">'
            '<rect x="3" y="6" width="18" height="14" rx="2"/>'
            '<circle cx="12" cy="13" r="3.5"/>'
            '<path d="M9 6l1-2h4l1 2"/></svg>'
            '<div style="font-size:7pt;">写真<br>(縦40×横30mm)</div>'
        )

    return f"""
<div style="max-width:170mm; margin:0 auto;">
  <h1 style="text-align:center; font-size:16pt; letter-spacing:0.3em; margin-bottom:8px; color:#1e3a5f;">
    履　歴　書
  </h1>

  <div style="display:flex; gap:8px; align-items:flex-start; margin-bottom:6px;">
    <table style="flex:1;">
      <tr>
        <th style="width:16%;">ふりがな</th>
        <td style="width:42%;">{_esc(p.get("name_kana", ""))}</td>
        <th style="width:12%;">性別</th>
        <td style="width:30%;">{_esc(p.get("gender", ""))}</td>
      </tr>
      <tr>
        <th>氏名</th>
        <td style="font-size:13pt; font-weight:bold;">{_esc(p.get("name_kanji", ""))}</td>
        <th>生年月日</th>
        <td>{_esc(p.get("date_of_birth", ""))}（満{p.get("age", "")}歳）</td>
      </tr>
      <tr>
        <th>住所</th>
        <td colspan="3">{_esc(p.get("address", ""))}</td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td>{_esc(p.get("phone", ""))}</td>
        <th>メール</th>
        <td>{_esc(p.get("email", ""))}</td>
      </tr>
      <tr>
        <th>国籍・ビザ</th>
        <td colspan="3">{_esc(visa_line)}</td>
      </tr>
    </table>
    <div style="{photo_box_style}">
      {photo_box_inner}
    </div>
  </div>

  <p class="section-title">学歴・職歴</p>
  <table>
    <thead>
      <tr><th style="width:22%;">年月</th><th>内容</th></tr>
    </thead>
    <tbody>
      <tr><td colspan="2" style="text-align:center; font-weight:bold;">学歴</td></tr>
      {education_rows}
      <tr><td colspan="2" style="text-align:center; font-weight:bold;">職歴</td></tr>
      {work_rows}
      <tr><td colspan="2" style="text-align:right;">以上</td></tr>
    </tbody>
  </table>

  <p class="section-title">資格・免許</p>
  <ul style="padding-left:1.2em; margin:4px 0;">{qualifications}</ul>

  <p class="section-title">特技・趣味</p>
  <div style="padding:4px; font-size:10pt;">
    <p style="margin:2px 0;"><strong>趣味：</strong>{_esc(p.get("hobbies") or "")}</p>
    <p style="margin:2px 0;"><strong>特技：</strong>{_esc(p.get("special_skills") or "")}</p>
  </div>

  <p class="section-title">自己PR</p>
  <p style="white-space:pre-wrap; padding:4px;">{_esc(c.get("self_pr", ""))}</p>

  <p class="section-title">志望動機</p>
  <p style="white-space:pre-wrap; padding:4px;">{_esc(c.get("motivation", ""))}</p>

  <p class="section-title">本人希望記入欄</p>
  <p style="white-space:pre-wrap; padding:4px;">{_esc(p.get("personal_requests", ""))}</p>
</div>
"""


def _render_shokumu(c: dict[str, Any]) -> str:
    skills = c.get("skills", {})

    def skill_items(items: list[str]) -> str:
        return "　／　".join(_esc(s) for s in items) if items else "―"

    companies_html = ""
    for company in c.get("companies", []):
        roles_html = ""
        for role in company.get("roles", []):
            responsibilities = "".join(
                f"<li>{_esc(r)}</li>" for r in role.get("responsibilities", [])
            )
            achievements = (
                "".join(f"<li>{_esc(a)}</li>" for a in role.get("achievements", [])) or "<li>―</li>"
            )
            roles_html += f"""
  <table style="margin-bottom:4px;">
    <tr>
      <th style="width:20%;">役職・職種</th>
      <td style="width:46%; font-weight:bold;">{_esc(role.get("role", ""))}</td>
      <th style="width:14%;">在籍期間</th>
      <td>{_esc(role.get("period_start", ""))} 〜 {_esc(role.get("period_end", ""))}</td>
    </tr>
  </table>
  <p class="label">【業務内容】</p>
  <ul style="padding-left:1.2em; margin:2px 0 6px;">{responsibilities}</ul>
  <p class="label">【実績・成果】</p>
  <ul style="padding-left:1.2em; margin:2px 0;">{achievements}</ul>
"""
        companies_html += f"""
<div style="margin-bottom:12px; padding-bottom:8px; border-bottom:1px solid #ccc;">
  <table style="margin-bottom:4px;">
    <tr>
      <th style="width:20%;">会社名</th>
      <td style="width:46%; font-weight:bold;">{_esc(company.get("company_name", ""))}</td>
      <th style="width:14%;">業種</th>
      <td>{_esc(company.get("industry", ""))}</td>
    </tr>
    <tr>
      <th>従業員数</th>
      <td colspan="3">{_esc(company.get("employee_count", ""))}</td>
    </tr>
  </table>
  {roles_html}
</div>
"""

    return f"""
<div style="max-width:170mm; margin:0 auto;">
  <h1 style="font-size:15pt; border-bottom:3px solid #1e3a5f; padding-bottom:4px; margin-bottom:8px; color:#1e3a5f;">
    職務経歴書
  </h1>

  <p class="section-title">職務要約</p>
  <p style="white-space:pre-wrap; padding:4px; margin-bottom:10px;">
    {_esc(c.get("summary", ""))}
  </p>

  <p class="section-title">職務経歴</p>
  {companies_html}

  <p class="section-title">スキル</p>
  <table style="margin-bottom:10px;">
    <tr>
      <th style="width:22%;">技術スキル</th>
      <td>{skill_items(skills.get("technical", []))}</td>
    </tr>
    <tr>
      <th>語学</th>
      <td>{skill_items(skills.get("languages", []))}</td>
    </tr>
    <tr>
      <th>その他</th>
      <td>{skill_items(skills.get("other", []))}</td>
    </tr>
  </table>

  <p class="section-title">自己PR</p>
  <p style="white-space:pre-wrap; padding:4px; margin-bottom:10px;">
    {_esc(c.get("self_pr", ""))}
  </p>

  <p class="section-title">志望動機</p>
  <p style="white-space:pre-wrap; padding:4px;">
    {_esc(c.get("motivation", ""))}
  </p>
</div>
"""


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------


def _feature_name(document_type: DocumentType) -> str:
    return "rirekisho" if document_type == DocumentType.rirekisho else "shokumu"


def _esc(value: Any) -> str:
    """HTML-escape a string value safely."""
    import html

    return html.escape(str(value)) if value is not None else ""


# Singleton
document_generator = DocumentGenerator()
