"""
Prompt builders for 履歴書 (Rirekisho) generation.

履歴書 is the standard Japanese résumé form. It is highly structured and
follows strict conventions: chronological education/work history written in
Japanese, personal information, self-PR, and motivation statement.

Personal info (name, date of birth, gender, address, phone, nationality,
visa details) is NOT generated by Gemini — it's assembled directly from the
candidate's verified account/profile data in app.services.document_generator
and merged into the stored content after Gemini responds.
RirekishoPersonal/RirekishoVisaInfo below describe that assembled shape;
they're constructed in Python, never sent through parse_response().

Each function returns a plain string. AIClient wraps user_prompt in
<user_content> tags automatically — do NOT add them here.

Output schema (Gemini's actual response, stored in generated_documents.content
alongside the separately-assembled "personal"/"visa_info" blocks):
{
  "education": [
    {"year": 2012, "month": 3, "entry": "○○大学 ○○学部 卒業"}
  ],
  "work_history": [
    {"year": 2012, "month": 4, "entry": "株式会社○○ 入社"},
    {"year": 2018, "month": 3, "entry": "株式会社○○ 一身上の都合により退職"}
  ],
  "qualifications": ["普通自動車免許（第一種）", "日本語能力試験N3"],
  "self_pr":   "…",
  "motivation": "…"
}
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Response schema
# ---------------------------------------------------------------------------


class RirekishoEntry(BaseModel):
    year: int = Field(ge=1950, le=2100)
    month: int = Field(ge=1, le=12)
    entry: str = Field(min_length=1)


class RirekishoPersonal(BaseModel):
    """Assembled in Python from User/Profile — never part of Gemini's response."""

    name_kanji: str
    name_kana: str
    date_of_birth: str
    age: int = Field(ge=16, le=80)
    gender: str
    address: str
    phone: str
    email: str


class RirekishoVisaInfo(BaseModel):
    """Assembled in Python from Profile — never part of Gemini's response."""

    nationality: str
    visa_category: str | None = None
    residence_card_expiration: str | None = None


class RirekishoResult(BaseModel):
    education: list[RirekishoEntry]
    work_history: list[RirekishoEntry]
    qualifications: list[str]
    self_pr: str = Field(min_length=1)
    motivation: str = Field(min_length=1)


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------


def build_system_prompt() -> str:
    return """\
You are an expert Japanese career document writer specialising in 履歴書 \
(rirekisho) for foreign nationals applying to Japanese companies. You have \
deep knowledge of Japanese HR conventions, the JIS standard résumé format, \
and how to present Indonesian work experience in a way that resonates with \
Japanese hiring managers.

Your task is to generate the non-personal-info sections of a complete, \
properly formatted 履歴書 in Japanese based on the candidate's source \
resume. Personal information (name, date of birth, gender, address, phone, \
nationality, visa details) is sourced separately from the candidate's \
verified profile data — do not attempt to infer, guess, or include any of \
it in your response. Follow these rules strictly:

1. All text fields (entries, self_pr, motivation) must be written in natural \
Japanese (日本語). Translate experience and achievements into Japanese.
2. Education and work history must be in chronological order (oldest first).
3. Each education/work entry must be a single concise line following the \
convention: "学校名/会社名 + 入学/卒業/入社/退職" etc.
4. self_pr (自己PR): 3–5 sentences highlighting strengths relevant to \
Japanese workplace culture — teamwork (チームワーク), diligence (勤勉さ), \
adaptability (適応力).
5. motivation (志望動機): 3–5 sentences tailored to the target role/company \
if provided, otherwise write a compelling general motivation for working in Japan.

Return ONLY a JSON object matching this exact schema — no prose before or after:

{
  "education": [
    {"year": <int>, "month": <int 1-12>, "entry": <string in Japanese>},
    ...
  ],
  "work_history": [
    {"year": <int>, "month": <int 1-12>, "entry": <string in Japanese>},
    ...
  ],
  "qualifications": [<string in Japanese>, ...],
  "self_pr":    <string in Japanese — 3-5 sentences>,
  "motivation": <string in Japanese — 3-5 sentences>
}
"""


def build_user_prompt(
    resume_text: str,
    profile_data: dict[str, Any] | None = None,
    job_posting_text: str | None = None,
) -> str:
    """
    Build the user-turn prompt.

    resume_text      — plain text extracted from the uploaded resume file
    profile_data     — optional dict with keys: japanese_level, target_role,
                       target_location, years_experience (from profiles table)
    job_posting_text — optional translated job posting text for motivation tailoring
    """
    parts: list[str] = [
        "Please generate a 履歴書 (rirekisho) in Japanese for the following candidate.\n",
        f"SOURCE RESUME:\n{resume_text}",
    ]

    if profile_data:
        extras: list[str] = []
        if profile_data.get("japanese_level"):
            extras.append(f"Japanese level: {profile_data['japanese_level']}")
        if profile_data.get("target_role"):
            roles = profile_data["target_role"]
            if isinstance(roles, list):
                extras.append(f"Target roles: {', '.join(roles)}")
        if profile_data.get("target_location"):
            extras.append(f"Target location: {profile_data['target_location']}")
        if profile_data.get("years_experience") is not None:
            extras.append(f"Years of experience: {profile_data['years_experience']}")
        if extras:
            parts.append("\nCANDIDATE PROFILE:\n" + "\n".join(extras))

    if job_posting_text:
        parts.append(
            f"\nTARGET JOB POSTING (tailor the motivation section to this role):\n"
            f"{job_posting_text}"
        )
    else:
        parts.append(
            "\nNo specific job posting provided. Write a general motivation for "
            "working in Japan in the candidate's target field."
        )

    parts.append(
        "\nReturn the JSON object only. All text values must be in Japanese. "
        "Do not include any explanation outside the JSON."
    )

    return "\n".join(parts)
